### ISSUE TITLE
Why schedule only on Main Dispatcher?

### ISSUE THREAD

**Issue by lwj1994** [wurensen/TaskScheduler#1]
maybe multi thread is faster?  is hard to solve the concurrency problem?

**Comment by wurensen** [comment]
任务调度doOnScheduled为suspend函数对象，执行在主线程，具体任务执行由开发者自行决定执行在什么线程，doOnScheduled调度执行结束表示任务结束，将进行后续的调度。
这样设计是基于几点考虑的：
1. 因为用于Android场景，所以调用及回调在主线程，可以避免使用者重新切线程
2. 依赖任务的调度在同一条线程可以直接保证是线程安全的
3. 通过协程挂起的方式，如果是耗时任务，可以由使用者自行决定在什么线程来执行
